import { Drawer } from '@/components/Drawer';
import { Footer } from '@/components/Footer/Footer';
import { Header } from '@/components/Header/Header';
import { DrawerProvider } from '@/contexts/DrawerContext';
import { ThemeProvider } from '@/contexts/ThemeContext';
import '@/styles/globals.scss';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja" suppressHydrationWarning>
      <body>
        {/* スタイルボタンのコンテキストプロバイダーでラップ */}
        <ThemeProvider>
          {/* ドロワーメニューのコンテキストプロバイダーでラップ */}
          <DrawerProvider>
            <Header />
            <main>
              <div className="container">{children}</div>
            </main>
            <Drawer />
          </DrawerProvider>
        </ThemeProvider>
        <Footer />
      </body>
    </html>
  );
}
