import { Drawer, DrawerRoot } from '@/components/Drawer';
import { Footer } from '@/components/Footer/Footer';
import { Header } from '@/components/Header/Header';
import { StyleButtonRoot } from '@/components/StyleButton';
import '@/styles/globals.scss';
import type { Metadata } from 'next';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body>
        {/* スタイルボタンのコンテキストプロバイダーでラップ */}
        <StyleButtonRoot>
          {/* ドロワーメニューのコンテキストプロバイダーでラップ */}
          <DrawerRoot>
            <Header />
            <main>
              <div className="container">{children}</div>
            </main>
            <Drawer />
          </DrawerRoot>
        </StyleButtonRoot>
        <Footer />
      </body>
    </html>
  );
}
